use_frameworks!

platform :ios, '8.0'

target 'TTPopView_Example' do
  pod 'TTPopView', :path => '../'

  target 'TTPopView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
